### ISSUE TITLE
Change to Eur

### ISSUE THREAD

**Issue by Juleship** [css459/cryptick#1]
I'd love to change to EUR or BTC conversions on the settings instead of just USD!

**Comment by css459** [comment]
I definitely plan to get this into the next update. Look out for it in the next week or so! 

Take care, 
Cole

**Comment by css459** [comment]
Added in commit fefc5db97eb1d68e35f8bb32bebf078ab0369099

Will be pushed to App Store in next update!

**Comment by tbnv** [comment]
Any idea when the update could be pushed to the App Store?
Can't wait to use it but USD is not helping… 🙂

**Comment by css459** [comment]
Version 1.2 just got approved for the App Store so it'll be available in the next couple hours! :)

**Comment by tbnv** [comment]
Awesome!
